"""Pydantic schemas and request models."""

from datetime import datetime
from typing import Literal, Optional

from pydantic import BaseModel, Field


# ── Internal Storage Models ───────────────────────────────────────────────────
class UserProfile(BaseModel):
    """Data stored in the SQLite User Profile persistence layer."""
    user_id: str
    name: str
    city: str           # e.g. 'Bengaluru'
    lat: float
    lon: float
    timezone: str       # e.g. 'Asia/Kolkata'
    unit_system: Literal["metric", "imperial"]
    language: str       # e.g. 'en'
    created_at: datetime


# ── Response Schemas (LLM Output Enforced) ──────────────────────────────────
class WeatherResponse(BaseModel):
    """Structured weather response format generated by the LLM."""
    temperature: float = Field(description="Current temperature in user units")
    feels_like: float = Field(description="Feels-like temperature")
    condition: str = Field(description="Short weather condition label")
    summary: str = Field(description="One-sentence natural language summary")
    location: str = Field(description="City and country code")
    humidity: int = Field(description="Relative humidity percentage")
    wind_speed: float = Field(description="Wind speed in user units")
    unit: Literal["metric", "imperial"]


class AssistantResponse(BaseModel):
    """Universal structured assistant response format."""
    intent: str = Field(description="Detected user intent (e.g. weather_query, general_chat, vision_request)")
    content: str = Field(description="Main assistant reply")
    data: Optional[WeatherResponse] = Field(default=None, description="Optional structured payload for specific tools (like weather)")
    follow_up: Optional[str] = Field(default=None, description="Optional follow-up question to keep the user engaged")


# ── Client Request Models ─────────────────────────────────────────────────────
class ChatRequest(BaseModel):
    """Expected payload for POST /chat and /chat/image"""
    message: str
    thread_id: str
